steps:
  # This step runs the unit tests on the app
  # - name: "python:3.7-slim"
  #   id: Test
  #   entrypoint: /bin/sh
  #   args:
  #     - -c
  #     - "pip install flask && python test_app.py -v"

  # This step builds the container image.
  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build production image
    args:     
      - "--dockerfile"
      - "docker/Dockerfile"
      - "--destination"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "--cache=true"

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build test image
    args:     
      - "--dockerfile"
      - "docker/Dockerfile.test"
      - "--destination"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:test-$SHORT_SHA"
      - "--cache=true"
  
  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:test-$SHORT_SHA"
    id: Run test
    dir: /barchart_import
  
  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:test-$SHORT_SHA"
    id: Check code quality
    dir: /barchart_import
    entrypoint: /barchart_import/check-codequality.sh



  - name: gcr.io/cloud-builders/gcloud
    id: Add branch name tag to production image
    entrypoint: "bash"
    args: ["-c","gcloud container images add-tag gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME"]

  - name: "gcr.io/kaniko-project/executor:latest"
    id: Build Pulumi Deployer
    args:
      - "--dockerfile"
      - "docker/Dockerfile.deployer"
      - "--destination"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:builder-$SHORT_SHA"
      - "--cache=$_DOCKER_CACHE"




  - name: gcr.io/cloud-builders/gcloud
    id: Add branch name tag to builder image
    entrypoint: "bash"
    args: ["-c","gcloud container images add-tag gcr.io/$PROJECT_ID/$REPO_NAME:builder-$SHORT_SHA gcr.io/$PROJECT_ID/$REPO_NAME:builder-$BRANCH_NAME"]

  - name: gcr.io/cloud-builders/gcloud
    id: Decrypt pulumi secret
    entrypoint: "bash"
    args: ["-c","gcloud secrets versions access latest --secret=PULUMI_ACCESS_KEY > pulumi-secret.txt"] 

  - name: gcr.io/cloud-builders/gcloud
    id: Decrypt secret
    entrypoint: "bash"
    args: ["-c","gcloud secrets versions access latest --secret=BARCHART_PASSWORD > barchart-password.txt"]

  - name: "gcr.io/$PROJECT_ID/$REPO_NAME:builder-$SHORT_SHA"
    id: Pulumi Create Stack
    entrypoint: "./scripts/build/create-stack-during-build.sh"
    args:
      - $BRANCH_NAME
      - "1051047723573"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "artifacts.unusual-option-activity-qaroot.appspot.com"
      - $_BARCHART_USERNAME
    env:
      - "BUILD_TYPE=$_BUILD_TYPE"
      - "TF_TRACE=TRACE"

substitutions:
  _BARCHART_USERNAME: ahoiahui@mail.bg # default value
  _DOCKER_CACHE: "true"